import type { IconType } from "react-icons";
import {
  SiBun,
  SiNestjs,
  SiPostgresql,
  SiVercel,
  SiMongodb,
  SiSupabase,
  SiPrisma,
  SiTailwindcss,
  SiJavascript,
  SiExpress,
  SiNodedotjs,
  SiTypescript,
  SiNextdotjs,
  SiRedux,
  SiReact,
  SiDocker,
  SiFigma,
  SiGit,
  SiGithub,
  SiHtml5,
  SiCss,
  SiLaravel,
  SiPhp,
  SiMysql,
  SiPython,
  SiVuedotjs,
  SiThreedotjs,
} from "react-icons/si";
import { LuGithub, LuFigma, LuCode, LuShieldCheck } from "react-icons/lu";
import { FaAws, FaReact, FaDocker, FaHtml5, FaCss3Alt } from "react-icons/fa6";
/** Small explicit catalog; unknown names retain a neutral icon instead of importing every icon pack. */
export const skillIcons: Record<string, IconType> = {
  SiBun,
  SiNestjs,
  SiPostgresql,
  SiVercel,
  SiMongodb,
  SiSupabase,
  SiPrisma,
  SiTailwindcss,
  SiJavascript,
  SiExpress,
  SiNodedotjs,
  SiTypescript,
  SiNextdotjs,
  SiRedux,
  SiReact,
  SiDocker,
  SiFigma,
  SiGit,
  SiGithub,
  SiHtml5,
  SiCss,
  SiLaravel,
  SiPhp,
  SiMysql,
  SiPython,
  SiVuedotjs,
  SiThreedotjs,
  LuGithub,
  LuFigma,
  LuShieldCheck,
  FaAws,
  FaReact,
  FaDocker,
  FaHtml5,
  FaCss: FaCss3Alt,
  DiVisualstudio: LuCode,
};
